defaults:
    target:
        host: www.google.com
        scheme: http://

Sections:
    website:
        rules:
            - HttpHeaderXSSProtectionSecure
            - HttpHeaderExposeLanguage
            - HttpHeaderContentTypeNoSniffing
            - HttpHeaderCookieWithHttpOnlyFlag
