defaults:
    target:
        host: www.example.host
        scheme: http://

Sections:
    main:
        config:
            scheme: https://
            host: www.example2.host
        rules:
            - HttpHeaderXSSProtection
            - HttpHeaderExposePHP
