Rules:
    HttpHeaderXSSProtectionPresent:
        class: \Frickelbruder\KickOff\Rules\HttpHeaderPresent
        calls:
            - ["setName", ["HttpHeaderXSSProtection"]]
            - ["setHeaderToSearchFor", ["X-XSS-Protection"]]

    HttpHeaderXSSProtectionSecure:
        class: \Frickelbruder\KickOff\Rules\HttpHeaderHasValue
        calls:
            - ["setName", ["HttpHeaderXSSProtection"]]
            - ["setHeaderToSearchFor", ["X-XSS-Protection"]]
            - ["setValue", ["1; mode=block"]]

    HttpHeaderExposePHP:
        class: \Frickelbruder\KickOff\Rules\HttpHeaderNotPresent
        calls:
            - ["setName", ["HttpHeaderExposePHP"]]
            - ["setHeaderToSearchFor", ["X-Powered-By"]]

    HttpRequestTime:
        class: \Frickelbruder\KickOff\Rules\HttpRequestTime

    HttpHeaderHasFarFutureExpiresHeader:
        class: \Frickelbruder\KickOff\Rules\HttpHeaderHasFarFutureExpiresHeader

    HttpHeaderResourceFound:
        class: \Frickelbruder\KickOff\Rules\HttpHeaderStatusCode
        calls:
            - ["setValue", ["200"]]

    HttpHeaderResourceIsMissing:
        class: \Frickelbruder\KickOff\Rules\HttpHeaderStatusCode
        calls:
            - ["setValue", ["404"]]

    HttpHeaderResourceIsGzipped:
        class: \Frickelbruder\KickOff\Rules\HttpHeaderHasValue
        calls:
            - ["setName", ["HttpHeaderResourceIsGzipped"]]
            - ["setHeaderToSearchFor", ["Content-Encoding"]]
            - ["setValue", ["gzip"]]

    HttpHeaderContentTypeNoSniffing:
        class: \Frickelbruder\KickOff\Rules\HttpHeaderHasValue
        calls:
            - ["setName", ["HttpHeaderContentTypeNoSniffing"]]
            - ["setHeaderToSearchFor", ["X-Content-Type-Options"]]
            - ["setValue", ["nosniff"]]

    HttpHeaderFrameOptionsSameOrigin:
        class: \Frickelbruder\KickOff\Rules\HttpHeaderHasValue
        calls:
            - ["setName", ["HttpHeaderFrameOptionsSameOrigin"]]
            - ["setHeaderToSearchFor", ["X-Frame-Options"]]
            - ["setValue", ["SAMEORIGIN"]]

    HttpHeaderCookieWithHttpOnlyFlag:
        class: \Frickelbruder\KickOff\Rules\HttpHeaderHasValue
        calls:
            - ["setName", ["HttpHeaderCookieWithHttpOnlyFlag"]]
            - ["setHeaderToSearchFor", ["Set-Cookie"]]
            - ["setExactMatch", [false]]
            - ["setValue", ["; HttpOnly"]]

    HttpHeaderCookieWithHttpSecureFlag:
        class: \Frickelbruder\KickOff\Rules\HttpHeaderHasValue
        calls:
            - ["setName", ["HttpHeaderCookieWithHttpSecureFlag"]]
            - ["setHeaderToSearchFor", ["Set-Cookie"]]
            - ["setExactMatch", [false]]
            - ["setValue", ["; Secure"]]

    #Better use HttpHeaderHSTSWithSubdomains
    HttpHeaderHSTSPresent:
        class: \Frickelbruder\KickOff\Rules\HttpHeaderPresent
        calls:
            - ["setName", ["HttpHeaderHSTSPresent"]]
            - ["setHeaderToSearchFor", ["Strict-Transport-Security"]]

    HttpHeaderHSTSWithSubdomains:
        class: \Frickelbruder\KickOff\Rules\HttpHeaderHasValue
        calls:
            - ["setName", ["HttpHeaderHSTSWithSubdomains"]]
            - ["setHeaderToSearchFor", ["Strict-Transport-Security"]]
            - ["setExactMatch", [false]]
            - ["setValue", ["; includeSubDomains"]]

    TitleTagLength:
        class: \Frickelbruder\KickOff\Rules\TitleTagLength

    MetaDescriptionLength:
        class: \Frickelbruder\KickOff\Rules\MetaDescriptionLength

