Rules:
    HttpHeaderXSSProtection:
        class: \Frickelbruder\KickOff\Rules\HttpHeaderPresent
        calls:
            - ['setHeaderToSearchFor', ["X-XSS-Protection"]]

    HttpHeaderExposePHP:
        class: \Frickelbruder\KickOff\Rules\HttpHeaderNotPresent
        calls:
            - ['setHeaderToSearchFor', ["X-Powered-By"]]
