Rules:
    HttpHeaderXSSProtection:
        class: \Frickelbruder\KickOff\Rules\HttpHeaderPresent
        calls:
            - ["setName", ["HttpHeaderXSSProtection"]]
            - ["setHeaderToSearchFor", ["X-XSS-Protection"]]

    HttpHeaderExposePHP:
        class: \Frickelbruder\KickOff\Rules\HttpHeaderNotPresent
        calls:
            - ["setName", ["HttpHeaderExposePHP"]]
            - ["setHeaderToSearchFor", ["X-Powered-By"]]

    HttpHeaderHasFarFutureExpiresHeader:
        class: \Frickelbruder\KickOff\Rules\HttpHeaderHasFarFutureExpiresHeader

    HttpHeaderResourceFound:
        class: \Frickelbruder\KickOff\Rules\HttpHeaderStatusCode
        calls:
            - ["setValue", ["200"]]

    HttpHeaderResourceIsMissing:
        class: \Frickelbruder\KickOff\Rules\HttpHeaderStatusCode
        calls:
            - ["setValue", ["400"]]

    HttpHeaderResourceIsGzipped:
        class: \Frickelbruder\KickOff\Rules\HttpHeaderHasValue
        calls:
            - ["setName", ["HttpHeaderResourceIsGzipped"]]
            - ["setHeaderToSearchFor", ["Content-Encoding"]]
            - ["setValue", ["gzip"]]

    HttpHeaderContentTypeNoSniffing:
        class: \Frickelbruder\KickOff\Rules\HttpHeaderHasValue
        calls:
            - ["setName", ["HttpHeaderContentTypeNoSniffing"]]
            - ["setHeaderToSearchFor", ["X-Content-Type-Options"]]
            - ["setValue", ["nosniff"]]

    HttpHeaderFrameOptionsSameOrigin:
        class: \Frickelbruder\KickOff\Rules\HttpHeaderHasValue
        calls:
            - ["setName", ["HttpHeaderFrameOptionsSameOrigin"]]
            - ["setHeaderToSearchFor", ["X-Frame-Options"]]
            - ["setValue", ["SAMEORIGIN"]]

    HttpHeaderCookieWithHttpOnlyFlag:
        class: \Frickelbruder\KickOff\Rules\HttpHeaderHasValue
        calls:
            - ["setName", ["HttpHeaderCookieWithHttpOnlyFlag"]]
            - ["setHeaderToSearchFor", ["Set-Cookie"]]
            - ["setExactMatch", [false]]
            - ["setValue", ["; HttpOnly"]]

    HttpHeaderCookieWithHttpOnlyFlag:
        class: \Frickelbruder\KickOff\Rules\HttpHeaderHasValue
        calls:
            - ["setName", ["HttpHeaderCookieWithHttpOnlyFlag"]]
            - ["setHeaderToSearchFor", ["Set-Cookie"]]
            - ["setExactMatch", [false]]
            - ["setValue", ["; HttpOnly"]]

    TitleTagLength:
        class: \Frickelbruder\KickOff\Rules\TitleTagLength

    MetaDescriptionLength:
        class: \Frickelbruder\KickOff\Rules\MetaDescriptionLength

